package com.dlsc.demo.mapper;

import com.dlsc.demo.domain.Algorithm;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface AlgorithmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_cc_algorithm
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_cc_algorithm
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    int insert(Algorithm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_cc_algorithm
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    int insertSelective(Algorithm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_cc_algorithm
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    Algorithm selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_cc_algorithm
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    int updateByPrimaryKeySelective(Algorithm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_cc_algorithm
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    int updateByPrimaryKey(Algorithm record);

    /**
     * 查询所有的算法
     * @return 算法集合
     */
    List<Algorithm> selectAlgorithmlist();
}