package com.dlsc.demo.domain;


import java.util.Date;


public class Algorithm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_cc_algorithm.GUID
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_cc_algorithm.AL_NAME
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    private String alName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_cc_algorithm.AL_INFO
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    private String alInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_cc_algorithm.AL_LOGO
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    private String alLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_cc_algorithm.AL_TYPE
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    private String alType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_cc_algorithm.UPDATE_PERSON
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    private String updatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_cc_algorithm.UPDATE_TIME
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_cc_algorithm.MARKET_ID
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    private String marketId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_cc_algorithm.GUID
     *
     * @return the value of cp_cc_algorithm.GUID
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_cc_algorithm.GUID
     *
     * @param guid the value for cp_cc_algorithm.GUID
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_cc_algorithm.AL_NAME
     *
     * @return the value of cp_cc_algorithm.AL_NAME
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    public String getAlName() {
        return alName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_cc_algorithm.AL_NAME
     *
     * @param alName the value for cp_cc_algorithm.AL_NAME
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    public void setAlName(String alName) {
        this.alName = alName == null ? null : alName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_cc_algorithm.AL_INFO
     *
     * @return the value of cp_cc_algorithm.AL_INFO
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    public String getAlInfo() {
        return alInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_cc_algorithm.AL_INFO
     *
     * @param alInfo the value for cp_cc_algorithm.AL_INFO
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    public void setAlInfo(String alInfo) {
        this.alInfo = alInfo == null ? null : alInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_cc_algorithm.AL_LOGO
     *
     * @return the value of cp_cc_algorithm.AL_LOGO
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    public String getAlLogo() {
        return alLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_cc_algorithm.AL_LOGO
     *
     * @param alLogo the value for cp_cc_algorithm.AL_LOGO
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    public void setAlLogo(String alLogo) {
        this.alLogo = alLogo == null ? null : alLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_cc_algorithm.AL_TYPE
     *
     * @return the value of cp_cc_algorithm.AL_TYPE
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    public String getAlType() {
        return alType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_cc_algorithm.AL_TYPE
     *
     * @param alType the value for cp_cc_algorithm.AL_TYPE
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    public void setAlType(String alType) {
        this.alType = alType == null ? null : alType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_cc_algorithm.UPDATE_PERSON
     *
     * @return the value of cp_cc_algorithm.UPDATE_PERSON
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_cc_algorithm.UPDATE_PERSON
     *
     * @param updatePerson the value for cp_cc_algorithm.UPDATE_PERSON
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson == null ? null : updatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_cc_algorithm.UPDATE_TIME
     *
     * @return the value of cp_cc_algorithm.UPDATE_TIME
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_cc_algorithm.UPDATE_TIME
     *
     * @param updateTime the value for cp_cc_algorithm.UPDATE_TIME
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_cc_algorithm.MARKET_ID
     *
     * @return the value of cp_cc_algorithm.MARKET_ID
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    public String getMarketId() {
        return marketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_cc_algorithm.MARKET_ID
     *
     * @param marketId the value for cp_cc_algorithm.MARKET_ID
     *
     * @mbggenerated Mon May 20 18:02:36 CST 2019
     */
    public void setMarketId(String marketId) {
        this.marketId = marketId == null ? null : marketId.trim();
    }
}